// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwoctdfujgugwmsjptnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3b2N0ZGZ1amd1Z3dtc2pwdG5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNzU1MDcsImV4cCI6MjA2NDc1MTUwN30.AQNahsc19IDyTq4JrCFxGE-h9OW5uBSuZ3tbUMOVHlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);